#!/bin/sh

	curl --user admin:cd060faeac561a2de90487bfefe746da http://localhost:8080/job/my_php_app/build?token=autodeploy123


cd  'e:\ci_project\auto_deploy\'

docker stop helloworld
docker rm  helloworld
docker build -t hello_world -f $(pwd)/dockerfile .

#docker run -d --name helloworld -p 80:80 -v /$(pwd)/src/:/var/www/html/ hello_world
#docker run -d --name helloworld -p 5000:80 -v //e/ci_project/auto_deploy/src/:/var/www/html/  hello_world


#REM /e/ci_project/auto_deploy/BuildExcutable

Echo "test"
exit 0
